apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  annotations:
    openshift.io/display-name: llm
    serving.kserve.io/enable-prometheus-scraping: "true"
  labels:
    app: llm
    opendatahub.io/dashboard: 'true'
    #networking.knative.dev/visibility: cluster-local # to disable route creation
  name: llm
spec:
  predictor:
    minReplicas: 1
    maxReplicas: 1
    model:
      modelFormat:
        name: vllm
      resources:
        requests:
          cpu: "1"
          memory: 16Gi
          nvidia.com/gpu: "1"
        limits:
          cpu: "2"
          memory: 16Gi
          nvidia.com/gpu: "1"
      runtime: llm
      storage:
        key: aws-connection-models
        path: /vicuna/
