apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base/s3-job

patches:
- target: 
    kind: Job
    name: setup-s3
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/env/0/value
      value: "/data/nousllama2.txt"

