apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: frontend
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: ghcr.io/kwkoo/openai-rag
        env:
        - name: TMPDIR
          value: /data
        - name: EMBEDDINGS_MODEL_NAME
          value: all-MiniLM-L6-v2
        - name: RERANKER_MODEL_NAME
          value: BAAI/bge-reranker-base
        - name: USE_RERANKER
          value: "false"
        - name: OPENAI_API_BASE
          value: http://llm-internal:8012/v1
        - name: OPENAI_API_KEY
          value: EMPTY
        - name: MODEL
          value: /mnt/models
        - name: TOKENIZERS_PARALLELISM
          value: "false"
        - name: DB_URL
          value: http://milvus:19530
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: minio
              key: MINIO_ROOT_USER
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: minio
              key: MINIO_ROOT_PASSWORD
        - name: AWS_ENDPOINT_URL_S3
          value: "http://minio:9000"
        ports:
        - name: http
          containerPort: 8080
        livenessProbe:
          httpGet:
            path: /healthz
            port: http
        readinessProbe:
          httpGet:
            path: /healthz
            port: http
        volumeMounts:
        - name: data
          mountPath: /data
        resources:
          limits:
            nvidia.com/gpu: 1
      volumes:
      - name: data
        emptyDir: {}
      tolerations:
        - key: nvidia.com/gpu
          operator: Exists
          effect: NoSchedule
status: {}