apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: frontend
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: 'true'
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: ghcr.io/kwkoo/openai-rag
        env:
        - name: SOURCE_DIRECTORY
          value: /data/source_documents
        - name: EMBEDDINGS_MODEL_NAME
          value: all-MiniLM-L6-v2
        - name: OPENAI_API_BASE
          value: http://llm-predictor.demo.svc.cluster.local/v1
        - name: OPENAI_API_KEY
          value: EMPTY
        - name: MODEL
          value: /mnt/models
        - name: TOKENIZERS_PARALLELISM
          value: "false"
        - name: DB_URL
          value: http://milvus:19530
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: minio
              key: MINIO_ROOT_USER
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: minio
              key: MINIO_ROOT_PASSWORD
        - name: AWS_ENDPOINT_URL_S3
          value: "http://minio:9000"
        ports:
        - name: http
          containerPort: 8080
        livenessProbe:
          httpGet:
            path: /healthz
            port: http
        readinessProbe:
          httpGet:
            path: /healthz
            port: http
        resources:
          limits:
            nvidia.com/gpu: 1
      tolerations:
        - key: nvidia.com/gpu
          operator: Exists
          effect: NoSchedule
status: {}