---
apiVersion: v1
stringData:
  AWS_ACCESS_KEY_ID: XXX
  AWS_SECRET_ACCESS_KEY: XXX
kind: Secret
metadata:
  annotations:
    serving.kserve.io/s3-endpoint: "minio.demo.svc:9000"
    serving.kserve.io/s3-usehttps: "0"
  name: kserve-secret
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kserve-sa
secrets:
- name: kserve-secret
---
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  annotations:
    # note - ensure that you change the uid to the namespace uid + 1
    # https://github.com/kserve/kserve/blob/master/docs/OPENSHIFT_GUIDE.md#with-service-mesh-istio
    #
    # proj=demo
    # start_uid="$(oc get ns $proj -o jsonpath='{.metadata.annotations.openshift\.io/sa\.scc\.uid-range}' | cut -d / -f 1)"
    # init_uid=$(( start_uid + 1 ))
    #
    serving.kserve.io/storage-initializer-uid: "1000910001"
    serving.knative.openshift.io/enablePassthrough: "true"
    sidecar.istio.io/inject: "true"
    sidecar.istio.io/rewriteAppHTTPProvers: "true"
  name: llm
spec:
  predictor:
    serviceAccountName: kserve-sa
    containers:
    - name: kserve-container
      image: docker.io/vllm/vllm-openai:latest
      #image: docker.io/kserve/vllmserver:latest
      workingDir: /root
      args:
      - "--port"
      - "8080"
      - "--model"
      - "/mnt/models"
      command:
      - python3
      - "-m"
      - vllm.entrypoints.openai.api_server
      - "--trust-remote-code"
      #- vllm.entrypoints.api_server
      ports:
      - containerPort: 8080
        protocol: TCP
      env:
      - name: HOME # needed because we need to write to $HOME/.cache
        value: /root
      - name: PYTHONPATH
        value: /workspace
      - name: STORAGE_URI
        value: s3://models/phi/
      volumeMounts:
      - name: home
        mountPath: /root
      resources:
        limits:
          cpu: "2"
          memory: 24Gi
          nvidia.com/gpu: "1"
        requests:
          cpu: "2"
          memory: 24Gi
          nvidia.com/gpu: "1"
    volumes:
    - name: home
      emptyDir: {}
    tolerations:
      - key: nvidia.com/gpu
        value: "True"
        effect: NoSchedule