apiVersion: v1
kind: ServiceAccount
metadata:
  name: setup-s3
---
# apiVersion: rbac.authorization.k8s.io/v1
# kind: RoleBinding
# metadata:
#   name: admin
# roleRef:
#   apiGroup: rbac.authorization.k8s.io
#   kind: ClusterRole
#   name: admin
# subjects:
# - kind: ServiceAccount
#   name: setup-s3
---
apiVersion: batch/v1
kind: Job
metadata:
  name: setup-s3
spec:
  template:
    metadata:
      labels:
        job: setup-s3
    spec:
      serviceAccountName: setup-s3
      containers:
      - image: ghcr.io/kwkoo/s3-utils
        name: setup-s3
        command:
        - /bin/bash
        - "-c"
        - |
          mc alias set minio $AWS_ENDPOINT_URL_S3 $AWS_ACCESS_KEY_ID $AWS_SECRET_ACCESS_KEY

          echo "creating bucket..."
          mc mb minio/models

          echo "uploading model to bucket..."
          exec python3 ./s3_utils.py
        env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: minio
              key: MINIO_ROOT_USER
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: minio
              key: MINIO_ROOT_PASSWORD
        - name: AWS_ENDPOINT_URL_S3
          value: "http://minio:9000"
        - name: MC_INSECURE
          value: "true"
        - name: MODEL
          value: vicuna
        resources: {}
      restartPolicy: Never
status: {}
